### ISSUE TITLE
Can't login on peergos.net

### ISSUE THREAD

**Issue by jonaswre** [Peergos/Peergos#1002]
![image](https://user-images.githubusercontent.com/3731681/203714494-e7171bc5-1ef8-40dd-b6da-ac368844e9a8.png)

I'm getting the following error when logging in

**Comment by ianopolous** [comment]
That should only be shown if you are offline and try to login with a user you haven't logged in with on that browser yet. 

I assume you are online? Does it happen every time?

Does the same happen in incognito mode?

**Comment by ianopolous** [comment]
We've made some improvements that should fix this. Is it still happening?

**Comment by jonaswre** [comment]
Its resolved now. Thanks
