### ISSUE TITLE
Official downloads for `.jar` and `.exe` get stuck at 10 MB

### ISSUE THREAD

**Issue by dillfrescott** [Peergos/Peergos#1036]
![Screenshot 2023-03-12 173138](https://user-images.githubusercontent.com/56714680/224574909-5037d4e8-8e51-4c6e-b465-e30bb3e9efeb.png)

**Comment by ianopolous** [comment]
Is this downloading from https://peergos.net/public/peergos/releases ? Which browser?

**Comment by ianopolous** [comment]
Yep, something's up. We're looking into it.

**Comment by ianopolous** [comment]
This should be fixed now. There were some legacy issues with the "peergos" user.
