### ISSUE TITLE
updating pki mirror state & bitswap error

### ISSUE THREAD

**Issue by lopezwys** [Peergos/Peergos#1046]
Hi, I've been trying to setup Peergos on RPi 3B+ running Arch Linux ARM, I used `java -jar Peergos.jar daemon` with combinations of `-generate-token true` and `-log-to-console true`. I want to access it via localhost (at least initially until I figure out a domain).

Last entries in peergos.0.log file are:
May 05, 2023 4:07:23 PM peergos.server.corenode.MirrorCoreNode update
INFO: Updating pki mirror state... Please wait. This could take a minute or two
$(ipfs daemon) err: 2023-05-05T16:09:11.515Z	ERROR	bitswap	providerquerymanager/providerquerymanager.go:338	Received provider (12D3KooWHCy25j2RNyDreKYUVVRuLiuFX7NWn8HPBFc2rEepw3UU) for cid (bafyreidy73ejyuwzuaolux7x2u4q7csdqifhu7yfbi734uvzfqieqxgn7m) not requested
May 05, 2023 4:35:55 PM peergos.server.storage.IpfsWrapper stop
INFO: Stopping ipfs daemon

The bitswap error wasn't there in previous logs (at least in the ones I checked, but maybe I forgot to check the logs when I left this process running longer). Aside from this the only errors were about buffer size, but I'm not sure if that is the case.

I was thinking about a few more things, which aren't as important to me, but I'd appreciate any help:
- I'm not sure how to change the default directory for Peergos data, I know it's mentioned in readme, but I'd appreciate an example command.
- is it possible to use Peergos with a domain on alternative DNS root? I would like to use OpenNIC TLDs, according to the [wiki](https://wiki.opennic.org/opennic/tls) TLS certificates are at an experimental stage.

**Comment by ianopolous** [comment]
So it's never finished starting and printed the PEERGOS ascii art?

An example of changing the default dir is
> java -jar Peergos.jar daemon -PEERGOS_PATH /home/lopezwys/peergosdir

You can use Peergos with any domain (but you also don't need to). You will need to terminate TLS on something like nginx which then proxies to the peergos daemon on localhost. The reson you don't need a domain is that once your server is running and you've created the account there, you can log in through another peergos instance you run on a different machine and writes will be transparently proxied to your server.

**Comment by lopezwys** [comment]
Thanks for replying, I really appreciate your dedication to this project. 

> So it's never finished starting and printed the PEERGOS ascii art?

Yes, it never got past the pki stage and never printed ascii art. In console (without -log-to-console) the last entries were:
>Connection refused: connect retrieving api/v0/id
>Block allow listener for [...] on /127.0.0.1:8002

Regarding domain - is an instance on a local (user) machine necessary to use peergos? Or is there a way to setup a server instance and access peergos (to login, transfer files etc) using only web interface? I don't mind if it is necessary, but it would somewhat limit my scope of using peergos

Also I'm not sure if the java version I use is sufficient - I installed jre17-openjdk-headless, because I don't use any gui on the server machine.

**Comment by ianopolous** [comment]
The initial pki sync can currently take a ridiculously long time, like 30 minutes. This only happens the very first time you (successfully) run it though. So it might be you just need to wait longer. We've got a prototype of a new version that does this in 12s, but it's still a ways off merging. 

You don't need a local peergos instance to use it. It works fine just from a browser if you're okay trusting DNS and the TLS certificate authorities. 

jre17-openjdk-headless should be fine.

**Comment by lopezwys** [comment]
Thanks, I'll try leaving it running for an hour or a few. I'll update you when I have some more info.

**Comment by lopezwys** [comment]
Hi, looks like it took a few hours to sync the pki, as it printed the ascii art and provided a link with token. However, when I open this link on another machine it's unable to connect. I don't have much experience with selfhosting - is there anything I need to do to connect?

**Comment by ianopolous** [comment]
A few hours! Ugh. We need to get that speedup merged. 

The link is a localhost link presumably?

**Comment by lopezwys** [comment]
Yes, it's a localhost link. 
The long syncing time doesn't really bother me, I just wasn't expecting it.

**Comment by ianopolous** [comment]
A localhost link will only work on the same machine. We should make that clearer in the message.

**Comment by lopezwys** [comment]
Ah, that explains a lot. I should've thought about it earlier. Thanks for the help!
