### ISSUE TITLE
Applying Configuration to Daemon (Self-Hosting)

### ISSUE THREAD

**Issue by shareable-vision** [Peergos/Peergos#1152]
Hello! And thank you for your wonderful project.

I am attempting to self-host Peergos, and I am having a little trouble configuring the daemon, specifically setting the `IPFS_PATH` and `ipfs-api-address`. The server is already running a primary IPFS node with API running on port 5001, therefore I am hitting the "Address already in use" error.

I am new to Java, so forgive me for showing my ignorance, but I am attempting to configure with the following command:

`java -Djava.library.path=native-lib -jar ./Peergos_v0.17.0.jar daemon -ipfs-api-address /ip4/127.0.0.1/tcp/5002 -generate -token true`

What am I doing wrong?

Thank you again @ianopolous for your support and all your amazing work! 🙏

**Comment by shareable-vision** [comment]
Ok, I moved the primary IPFS node API to port 5002, and checked that 5001 was available, removed the Peergos-generated folders, and reinitialized.

Still getting "Address already in use", so my initial diagnosis was not correct.

I am still in need of a little assistance please, when you have time. Thank you

**Comment by shareable-vision** [comment]
Okay, I found [an example that solves the issue](https://github.com/Peergos/Peergos/issues/1090):

> I used java -jar Peergos.jar daemon -log-to-console true -ipfs-api-address /ip4/127.0.0.1/tcp/6001 -ipfs-gateway-address /ip4/127.0.0.1/tcp/9081 -ipfs-swarm-port 7001 so Peergos would start up.

Sorry for duplicating a solved issue.

**Comment by ianopolous** [comment]
Peergos uses a customised and much improved version of ipfs internally, so you can't run it with an external ipfs implementation.
