### ISSUE TITLE
Bug: misplaced IPFS_PATH

### ISSUE THREAD

**Issue by shareable-vision** [Peergos/Peergos#1154]
The default `IPFS_PATH` is not honored, when daemon is executed from $HOME, in which case IPFS is installed to `$HOME/home/ipfs/.ipfs`. This bug appears with username `peergos`, and I do not know if the same applies with other usernames or not. I was happy with would be the default locations, but not with having ipfs installed to `/home/peergos/home/ipfs/.ipfs`

**To work around the issue:**
 * `export IPFS_PATH=$HOME/.peergos/.ipfs`
 * And execute the daemon from `/` instead of `~`

To be clear (in my experience) _only_ setting `IPFS_PATH` is insufficient, and the daemon _must_ be executed from `/` in order to install IPFS to the expected location.

This works fine for me, but I thought I would make a note of it, as this may introduce confusion for new users of the Peergos daemon.

All is well. Thank you for creating Peergos!

**Comment by ianopolous** [comment]
I can't reproduce this. The ipfs dir should always be a subdir of the .peergos dir. The only case when it is not is when you manually set IPFS_PATH (via an arg or the env). Are you sure you aren't setting IPFS_PATH as an env var?

This is the relevant line: https://github.com/Peergos/Peergos/blob/master/src/peergos/server/storage/IpfsWrapper.java#L280

**Comment by shareable-vision** [comment]
Oh, how embarrassing . . 

You are absolutely right. I did have `IPFS_PATH` set, earlier in my profile.
Removing IPFS_PATH and PEERGOS_PATH from profile and double checking on the command-line, before running:

`java -Djava.library.path=native-lib -jar Peergos.jar daemon -ipfs-api-address /ip4/127.0.0.1/tcp/5002 -ipfs-gateway-address /ip4/127.0.0.1/tcp/8082 -ipfs-swarm-port 4002 -log-to-console true`

totally _works_ —provides the default locations as expected.

I apologize and thank you for your assistance.

**Comment by shareable-vision** [comment]
Oh, how embarrassing . . 

You are absolutely right. I did have `IPFS_PATH` set, earlier in my profile.
Removing IPFS_PATH and PEERGOS_PATH from profile and double checking on the command-line, before running:

`java -Djava.library.path=native-lib -jar Peergos.jar daemon -ipfs-api-address /ip4/127.0.0.1/tcp/5002 -ipfs-gateway-address /ip4/127.0.0.1/tcp/8082 -ipfs-swarm-port 4002 -log-to-console true`

totally _works_ —provides the default locations as expected.

I apologize and thank you for your assistance.

**Comment by ianopolous** [comment]
Thank you though. It's a good point as someone already running ipfs separately is reasonably likely to hit the same thing. We should probably use a different arg name
