### ISSUE TITLE
How to configure the remote instance of a local daemon?

### ISSUE THREAD

**Issue by rapenne-s** [Peergos/Peergos#1178]
Hi,

I wanted to try the local daemon to login into a remote server (the demo server for instance) to proxy all operations, but I fail to understand how to configure that remote instance

I've been following https://github.com/peergos/peergos?tab=readme-ov-file#usage---running-locally-to-log-in-to-another-instance , I created a new account on http://localhost:8000/

From there, I can use Peergos locally but I wanted to use my demo account (on https://peergos-demo.net ) to see if the proxy is really effective, before either signing up with a paid account or decide to self host my own peergos instance.

**Comment by rapenne-s** [comment]
I think I got the understanding of how it works. The demo server is certainly not federated right?

I self hosted a public server and I was able to use it with a local proxy.

However, I made a local proxy before and created an user there, I can't create it again on my new public server, does users expire? A DoS attack could consist of monopolizing all usernames if I get it right.

**Comment by ianopolous** [comment]
The demo server is on a separate network (it has its own PKI) you can join that network but you have to supply a few extra args. 
peergos.identity.hash 
pki-node-id
pki.node.ipaddress
pki.node.swarm.port

**Comment by ianopolous** [comment]
Usernames are globally unique yes, via the PKI. Signups are rate limited. In the longer term we plan to remove the PKI entirely and relax usernames to only be unique to an instance.

**Comment by rapenne-s** [comment]
> The demo server is on a separate network (it has its own PKI) you can join that network but you have to supply a few extra args. peergos.identity.hash pki-node-id pki.node.ipaddress pki.node.swarm.port

How can you get these information from a remote instance?

**Comment by rapenne-s** [comment]
> Usernames are globally unique yes, via the PKI. Signups are rate limited. In the longer term we plan to remove the PKI entirely and relax usernames to only be unique to an instance.
> 
> #1091

I see, is there a mechanism to purge a "reserved" username for an instance that does not exist anymore?

**Comment by ianopolous** [comment]
The demo server is its own pki, the args are:
-peergos.identity.hash z59vuwzfFDowHfWahauKKD2mZZAx14qGva4mUUwRRLX5tKiqvwhcukN
-pki-node-id z5AanNVJCxnL32nhyF8hbZKtEDDA9TdEXJGZiTTkcxiwpvfViuMivTE
-pki.node.ipaddress 139.162.184.68
-pki.node.swarm.port 4001

**Comment by ianopolous** [comment]
The is no mechanism to delete usernames from the PKI. It is similar to a certificate transparency log.

**Comment by rapenne-s** [comment]
Thanks for your replies

**Comment by ianopolous** [comment]
No worries, happy to answer any more questions. I'll probably reply faster in our public matrix channel.
