### ISSUE TITLE
[documentation] garbage collector

### ISSUE THREAD

**Issue by rapenne-s** [Peergos/Peergos#1185]
There is a command line parameter `-enable-gc true` is required to enable the garbage collection (off by default) and `-gc.period.millis` to configure the frequency. Both are not documented.

Ideally, I recommend to enable the garbage collector by default, the frequency is 12h by default which is fine for the average user.

Related to https://github.com/Peergos/Peergos/blob/43830fff4a74f3790f07092ac55ac3a418ad611a/src/peergos/server/Main.java#L546

**Comment by rapenne-s** [comment]
just to be sure, is https://github.com/Peergos/Peergos/commit/43830fff4a74f3790f07092ac55ac3a418ad611a still useful after #1189 ?

**Comment by ianopolous** [comment]
That's where we use the supplied parameter yes. Or are you referring to the false?
