### ISSUE TITLE
[bug] shell : mkdir and put "cannot parse command"

### ISSUE THREAD

**Issue by rapenne-s** [Peergos/Peergos#1190]
I built Peergos locally on Linux using git clone, I'm on commit ce5a3b0ad4f5e5652c11c4769b4e9fac58c40938

mkdir and put commands do not work in shell mode, I did not try other commands

```
rapenne-s@https://XXX > ls
/rapenne-s/CCCCC
rapenne-s@https://XXX > mkdir "dir"
Could not parse command.
rapenne-s@https://XXX > put /dev/Peergos/hello\ world 
Could not parse command.
```

I did not update the instance I'm connected to, it's using the build available on github.

**Comment by ianopolous** [comment]
Why are you quoting dir if it has no spaces?

The supported quoting is ""

**Comment by ianopolous** [comment]
There was another issue though, and that is fixed in master now.

**Comment by ianopolous** [comment]
And we support quoting something without any spaces now too.
