### ISSUE TITLE
Create the new static website

### ISSUE THREAD

**Issue by ianopolous** [Peergos/Peergos#120]

**Comment by nsomaru** [comment]
@ianopolous can you provide an indication of the requirements here?

**Comment by ianopolous** [comment]
Hi nsomaru, Welcome to Peergos!

This was meant to be for creating a new version of our website, which is up at https://peergos.org 
So I'll close this issue.

We can certainly do with help in many areas if you'd like to contribute. If so, then let me know what kind of things interest you and I'll see if I can find an appropriate task.
