### ISSUE TITLE
unblock domain error message

### ISSUE THREAD

**Issue by gyuri-lajos** [Peergos/Peergos#1211]
encountered this error this morning

On one of my machines ny hyperpost paid account appears to work
but attemoting to access certain files from another machine files are unaccessible

Peergos seemed to be pretty stable before. I am commited to use it, but this issue does worry me

![image](https://github.com/user-attachments/assets/0edda822-557c-4fef-9917-e06768a480c5)

**Comment by ianopolous** [comment]
Do you have anything like an adblocker that might be blocking the blockstore domain on that machine?

**Comment by ianopolous** [comment]
This should be fixed now.

**Comment by gyuri-lajos** [comment]
> everything should still work

additional information files were showing but CKEditor did not load on certain files

**Comment by gyuri-lajos** [comment]
Thank you for the quick resolution of the issue.

**Comment by gyuri-lajos** [comment]
resolved thank you
