### ISSUE TITLE
[Feature request] Free space threshold

### ISSUE THREAD

**Issue by rapenne-s** [Peergos/Peergos#1213]
Using the sync client mode, Peergos should stop trying to download files if the destination directory disk space is below a certain threshold (either MB or %, syncthing offers the two)

this will prevent borking some files in all running programs, because bad things happens on a full filesystem :/ (db in ~/.peergos/ were affected)

I guess keeping 1% or 100MB minimum would be a good default

**Comment by ianopolous** [comment]
Excellent idea.
