### ISSUE TITLE
How, what and ?

### ISSUE THREAD

**Issue by alugarius** [Peergos/Peergos#148]
I would like to see some instruction how to use this.

""First install and run the IPFS daemon
The run with the following to find out available options: java -jar PeergosServer.jar -help"""

is way to less information! ... where can i get the .jar file? do i have to build it? how do i build it? do i need other software?

it seems a good project, but without documentation i cant do anything with it.... please to a release or a tutorial!

**Comment by alugarius** [comment]
Ok, I didn't knew that you are busy with the coding, thanks for telling.
I hope you do great progress.

**Comment by ianopolous** [comment]
We've just done a big release to https://demo.peergos.net
It's not quite ready for self-hosting yet though.
