### ISSUE TITLE
Get it working in safari

### ISSUE THREAD

**Issue by ianopolous** [Peergos/Peergos#190]
Both on mac and iphones.

**Comment by kevodwyer** [comment]
noticed a couple of things:
DnD into peergos does not work.  Javascript error
TypeError: undefined is not an object (evaluating 'items.length')
dndDrop — peergos.js:149

Downloading does not work - Javascript error: failed to load resource: frame load interrupted
http://stackoverflow.com/questions/27979045/failed-to-load-resourceframe-load-interrupted-in-safari-browser-while-downloadi

**Comment by kevodwyer** [comment]
maybe https://github.com/eligrey/FileSaver.js/issues/12

**Comment by ianopolous** [comment]
Okay, let's change this to adding a warning on the front page if the browser is Safari, saying we don't support it and recommend Chrome.
