### ISSUE TITLE
Tagged releases and changelog

### ISSUE THREAD

**Issue by baimafeima** [Peergos/Peergos#251]
Could you tag your releases and make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by ianopolous** [comment]
We don't have any releases yet as it is still pre-alpha. Eventually, we plan on distributing releases through Peergos itself, and will be including content addressed links to the source, again hosted in Peergos.

**Comment by baimafeima** [comment]
Ok, thanks for the feedback. Looking forward to the first releases. Would be great to have additional releases on GitHub though as your website may be censored in some countries.
