### ISSUE TITLE
Signup error on demo site

### ISSUE THREAD

**Issue by cboddy** [Peergos/Peergos#285]
See screenshot below. Couldn't reproduce it after it happened though :/

Using chromium.

![screenshot from 2018-01-09 19-13-50](https://user-images.githubusercontent.com/1190179/34738659-a229d9b4-f571-11e7-9adf-37ef9e0d1e2d.png)

**Comment by ianopolous** [comment]
Is there a chance you refreshed the page after this error and before not being able to repro it?

**Comment by ianopolous** [comment]
(My first guess is that your browser had cached an old version with different properties, resulting in the error), otherwise we should try harder to reproduce this.
