### ISSUE TITLE
Which encryption did you use ?

### ISSUE THREAD

**Issue by maroodb** [Peergos/Peergos#339]
Hello World <br>
I want to know if did you use IPFS keys for encryption or you used an external library & keys ?

**Comment by ianopolous** [comment]
Neither. We use our own code and keys external to ipfs. We do not put any trust in ipfs.
For more information see our docbook:
https://peergos.github.io/book

**Comment by maroodb** [comment]
Ok. for read/write access control did you implement the cryptotree ?

**Comment by ianopolous** [comment]
Read access is controlled using cryptree. Write access is controlled using our equivalent to IPNS

**Comment by maroodb** [comment]
and how to implement a cryptree (javascript) ? is there a spec ?

**Comment by ianopolous** [comment]
The specs is basically the paper linked from our readme. We implemented it in Java and cross compiled to JS with gwt. 
The relevant Java classes are:
https://github.com/Peergos/Peergos/blob/master/src/peergos/shared/user/fs/DirAccess.java
https://github.com/Peergos/Peergos/blob/master/src/peergos/shared/user/fs/FileAccess.java
