### ISSUE TITLE
Fuzz Cryptree

### ISSUE THREAD

**Issue by ianopolous** [Peergos/Peergos#392]
Use a host filesystem and a self contained permission model that mirrors our expected semantics to fuzz cryptree. 

By this I mean create a model and a cryptree filesystem and set of users, and do random operations and compare the two file systems and user access after each. 

Operations including:
* write new file
* mkdir
* modify file
* delete a file/dir
* copy a file/dir
* grant (R/W) access to a n users to a file/dir
* revoke (R/W) access to a user

**Comment by kevodwyer** [comment]
actions to add: rm shared file, rm shared dir, rename shared file, rename shared dir
