### ISSUE TITLE
Figure out why text documents randomly don't open

### ISSUE THREAD

**Issue by ianopolous** [Peergos/Peergos#596]

**Comment by kevodwyer** [comment]
fix in https://github.com/Peergos/web-ui/pull/143

**Comment by ianopolous** [comment]
I also can't reproduce this anymore. so closing for now.

**Comment by ianopolous** [comment]
Just happened again.
Firefox 75. File size: 3016

**Comment by ianopolous** [comment]
This is hopefully fixed now. Reopen if not.
