### ISSUE TITLE
shared files (Fuzzer issue 2)

### ISSUE THREAD

**Issue by cboddy** [Peergos/Peergos#621]
Two users: left and right are reciprocally friends.

user `left`  writes `/left/some_dir/some_file`.
user `left` grants user `right` write-permission to `/left/some_dir/some_file`.

user right  cannot write  `/left/some_dir/some_file` - unless user right also has write-permission to the parent  dir `/left/some_dir`.

**Comment by ianopolous** [comment]
This is now fixed in master, with a unit test.
