### ISSUE TITLE
replication

### ISSUE THREAD

**Issue by ghost** [Peergos/Peergos#627]
We have a local server, on which we have successfully installed and run Peergos and we need the information that server has at the time of lifting the service is replicated on 4 more local servers, that if one falls, the other will be lifted, basically what we need is to know how or if the same information can be replicated from one server to another in the same farm

**Comment by ianopolous** [comment]
Note that the Peergos web-ui should NEVER be server up without TLS. The users are wide open to a MITM without TLS. 

You can mirror an entire node or just an individual user using the mirror.node.id or mirror.username options. This will mirror all the data in ipfs, and also create a local only copy of the mutable pointers. Note this is periodically synced, not real-time updated. This only leaves any pending follow requests and the ipfs identity keypair, which there currently isn't an automated mechanism to duplicate. 

The model in Peergos is that you have one logical storage server per user, which is identified by the public key of the ipfs instance. So you cannot migrate servers without that keypair.

**Comment by mauriciofgp01** [comment]
ok ask them if they can send you an example or what to modify to be able to add the servers in that key pair

**Comment by mauriciofgp01** [comment]
I can ask you for help with some manual or video guide that really does not work for me. I was looking at the support topic and ask for a donation. I already made it. I would very much like your help because it is a topic that worries me for a project

**Comment by mauriciofgp01** [comment]
pliz help

**Comment by ianopolous** [comment]
Are you planning on putting those servers behind TLS?

**Comment by mauriciofgp01** [comment]
if I can replicate the server, yes or what you recommend me

**Comment by ianopolous** [comment]
At the moment you can't easily replicate the server if you are trying to scale horizontally. You can mirror most of the data on another node as I described above. However, that can't be used as a hot failover, just as a backup. You will need to backup the ipfs keypair separately, which is in the ipfs config file.

**Comment by mauriciofgp01** [comment]
You can explain me in which part or send me an example of how to add or copy the pawmer IPFS to make the mirror in my other node (server) plz help

**Comment by mauriciofgp01** [comment]
You can explain me in which part or send me an example of how to add or copy the pawmer IPFS to make the mirror in my other node (server) plz help

**Comment by mauriciofgp01** [comment]
You can explain me in which part or send me an example of how to add or copy the pawmer IPFS to make the mirror in my other node (server) plz help

**Comment by mauriciofgp01** [comment]
sorry I don't know why he sent himself so many times

**Comment by mauriciofgp01** [comment]
You must make a backup copy of the ipfs key pair separately, which is located in the ipfs configuration file. Can you help me with a guide, manual or video on how to make this the best recommendations because I don't get it

**Comment by ianopolous** [comment]
If you want a secure installation I recommend using https://alpha.peergos.net.

The ipfs config is at $PEERGOS_INSTALL_DIR/.ipfs/config
$PEERGOS_INSTALL_DIR is ~/.peergos unless you have overridden it.

**Comment by mauriciofgp01** [comment]
yes I know that is the folder where everything is stored but then in that config file you have to add the node? from the other server? How can I know if the mirror is already working? How should the second node be run to do the test? Always on LAN or with public IP if you have a video manual or guide to do it

**Comment by ianopolous** [comment]
The mirror is only useful as a backup. If you shut down the original node, you would need to copy the ipfs keypair to the new node (the entire config file would be fine), as well as the pending follow requests, and quotas. Then start the new node. 

Why do you want multiple nodes? If it is for load balancing that is not currently possible.

**Comment by mauriciofgp01** [comment]
Why do you want multiple nodes? If it is to balance the load, that is not currently possible.
It is really like to support the information that is uploaded in the nodes and to be able to… have as a contingency if any node fails, but then it cannot.
Do you have any manual for the replication of the files and the users passwords space capacities and other configurations or a guide or if it can be done as a standard process at a specific time thanks for the help at least I better understand how to solve it in a way.

**Comment by ianopolous** [comment]
There are no passwords stored anywhere. 

You can only use the command line options to mirror that I explained above. Everything else has to be done manually.

**Comment by mauriciofgp01** [comment]
Any other recommendation or any other suggestion that you can help me and thanks for everything has been very helpful

**Comment by mauriciofgp01** [comment]
And as for when it is planned to update for replication and freight dive thanks for the help
