### ISSUE TITLE
how can i slove this problem when i run "ant run" command

### ISSUE THREAD

**Issue by alison-man** [Peergos/Peergos#632]
[exec] INFO: Scrypt hashing took: 1325 mS
     [exec] Feb 10, 2020 9:07:26 AM peergos.shared.crypto.hash.ScryptJava hashToKeyBytes
     [exec] INFO: Scrypt hashing took: 1150 mS
     [exec] Feb 10, 2020 9:07:26 AM peergos.shared.user.UserContext lambda$signUpGeneral$25
     [exec] INFO: Registering username peergos
     [exec] Feb 10, 2020 9:07:26 AM peergos.shared.user.UserContext register
     [exec] INFO: claiming username: peergos with expiry 2020-04-10
     [exec] Feb 10, 2020 9:07:26 AM peergos.server.net.DHTHandler handle
     [exec] INFO: DHT Handler handled id query in: 8 mS
     [exec] Feb 10, 2020 9:07:26 AM peergos.server.corenode.HttpCoreNodeServer$CoreNodeHandler handle
     [exec] INFO: Corenode server handled getChain request in: 2 mS
     [exec] java.util.concurrent.CompletionException: java.lang.IllegalStateException: **User already exists!**
     [exec] 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
     [exec] 	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1113)
     [exec] 	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
     [exec] 	at peergos.shared.user.UserContext.lambda$register$74(UserContext.java:647)
     [exec] 	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
     [exec] 	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
     [exec] 	at peergos.shared.user.UserContext.register(UserContext.java:645)
     [exec] 	at peergos.shared.user.UserContext.lambda$signUpGeneral$25(UserContext.java:230)
     [exec] 	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
     [exec] 	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
     [exec] 	at peergos.shared.user.UserContext.signUpGeneral(UserContext.java:222)
     [exec] 	at peergos.server.Main.poststrap(Main.java:194)
     [exec] 	at peergos.server.Main.lambda$static$4(Main.java:247)
     [exec] 	at peergos.server.Command.main(Command.java:73)

**Comment by ianopolous** [comment]
If you want to run Peergos I would download a release from
https://alpha.peergos.net/public/peergos/releases
or build a jar from the web-ui repo which includes this repo as a submodule. 
Then run it using the instructions here:
https://github.com/peergos/peergos#usage
