### ISSUE TITLE
I build web-ui at local and run it  how can i slove these problem

### ISSUE THREAD

**Issue by alison-man** [Peergos/Peergos#634]
(1)Error signing up with Google Chrome-80 but with Firefox normal?
err-msg: (TypeError):Cannot read property 'digest' of undefined

(2)I want more storage what's the next step when i send a more storage request?

thanks

**Comment by ianopolous** [comment]
After you request more storage, an admin on the instance you signed up to needs to approve it.

**Comment by ianopolous** [comment]
Closing as dupe of https://github.com/Peergos/Peergos/issues/637
