### ISSUE TITLE
Login error by use Google Chrome

### ISSUE THREAD

**Issue by alison-man** [Peergos/Peergos#637]
![image](https://user-images.githubusercontent.com/39581688/74637177-6dfcec80-51a4-11ea-889b-4d5d31093b8b.png)

thanks

**Comment by alison-man** [comment]
(TypeError) : Cannot read property 'digest' of undefined

**Comment by alison-man** [comment]
(TypeError) : Cannot read property 'digest' of undefined

**Comment by ianopolous** [comment]
Can you try a force refresh? (CTRL +F5)

**Comment by alison-man** [comment]
I try  (CTRL +F5) but the error still exisit---（chrome 80.0.3987.106）
 Login normal by use only firefox

**Comment by alison-man** [comment]
![image](https://user-images.githubusercontent.com/39581688/76080389-bfe5a500-5fe1-11ea-87a2-27d2490ab612.png)

**Comment by alison-man** [comment]
![image](https://user-images.githubusercontent.com/39581688/76080426-d55acf00-5fe1-11ea-860b-1840bbcc66ee.png)
why?!!!!

**Comment by ianopolous** [comment]
I can login fine with Chrome 80.0.3987.87 on Linux on the alpha server. Is this local or using one of our servers?

**Comment by ianopolous** [comment]
What OS is this on?

**Comment by alison-man** [comment]
CentOS-6.5
Install setp:
     checkout the project
     build the server
     build the web-ui
    start a local Peergos server on http://localhost:8000 for web-ui development in which all writes are local to memory

reverse proxy server Nginx
win10-chrome login error

**Comment by ianopolous** [comment]
Are you able to login to the demo server in the same browser? https://demo.peergos.net

**Comment by ianopolous** [comment]
Just to be sure, can you also try it in chrome without any plugins installed? (I noticed you have the vue plugin running - I don't think this matters, but want to rule it out.)

**Comment by alison-man** [comment]
thanks, mush!
yes, i can able to login to the demo server in the same browser https://demo.peergos.net

**Comment by ianopolous** [comment]
What commit are you on? The latest master?
