### ISSUE TITLE
Failed to load resource: the server responded with a status of 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by alison-man** [Peergos/Peergos#683]
@ianopolous 
hi, can you tell me how to solve this problem when i use nginx proxy to remote login
![image](https://user-images.githubusercontent.com/39581688/82420882-e54b6080-9ab2-11ea-87d5-a4ee572bdf11.png)

1. i used nginx proxy like "demo.peergos.com" but why about this error ?
or show your nginx.conf of proxy domain

2. only login normal when i use http://localhost:8000 on localhost

**Comment by alison-man** [comment]
ant update_and_run (mater web-ui)

**Comment by alison-man** [comment]
ant update_and_run (master web-ui)

**Comment by alison-man** [comment]
how can i use nginx proxy for localhost:8000 like demo.peergos.com

**Comment by ianopolous** [comment]
on localhost the api will only accept http POST, if you want to allow access on some other domain then you need to run the server with argument -public-server true. But note that this exposes the server to every website you visit on the same machine, because browsers allow any site to make get requests to localhost.

**Comment by ianopolous** [comment]
Note also that ant update_and_run will only run a local instance for testing.

**Comment by alison-man** [comment]
@ianopolous 
thanks a lot, but now has a new problem when i login in
![image](https://user-images.githubusercontent.com/39581688/82451196-3c1b5f00-9ae0-11ea-80e8-165180ba9b31.png)
log msg:
java.io.IOException:+Server+returned+HTTP+response+code:+405+for+URL:+http://127.0.0.1:8080/p2p/QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF/http/peergos/v0/mutable/getPointer?owner=z59vuwzfFDp3ZA8ZpnnmHEuMtyA1q34m3Th49DYXQVJntWpxdGrRqXi&writer=z59vuwzfFDp3ZA8ZpnnmHEuMtyA1q34m3Th49DYXQVJntWpxdGrRqXi

run server command:
java -jar Peergos.jar daemon -pki-node-id QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF -peergos.identity.hash z59vuwzfFDp3ZA8ZpnnmHEuMtyA1q34m3Th49DYXQVJntWpxdGrRqXi -logToConsole true -admin-usernames peergos peergos.password testpassword -useIPFS true -max-users 5 -public-server true

**Comment by ianopolous** [comment]
That's connecting to the alpha network, which we're not ready to support yet. You can connect to the demo network with:
> java -jar Peergos.jar daemon -pki-node-id QmdM1TrjBJnYzzESATtrrMNPAtjJdqfcV2vF1kM39DY7cc -peergos.identity.hash z59vuwzfFDoqvC6R5QBV4tXx6ZK3SytpvvcjKnWD2VXZXhxDbFq7Fuu -logToConsole true -admin-usernames $youruser -useIPFS true -max-users 5 -public-server true

What address are you viewing the web interface through? Is it localhost?
