### ISSUE TITLE
Error: cannot acquire lock

### ISSUE THREAD

**Issue by widwith** [Peergos/Peergos#712]
Thought I'd test this out and followed the instructions and downloaded latex Peergos.jar (v0.2.1) and started it:

java -jar Peergos.jar daemon -pki-node-id QmdM1TrjBJnYzzESATtrrMNPAtjJdqfcV2vF1kM39DY7cc -peergos.identity.hash z59vuwzfFDoqvC6R5QBV4tXx6ZK3SytpvvcjKnWD2VXZXhxDbFq7Fuu -logToConsole true

But get following error for peergos:

INFO: $(ipfs p2p listen --allow-custom-protocol /http /ip4/127.0.0.1/tcp/8000) err: Error: cannot acquire lock: Lock FcntlFlock of /home/user/.peergos/.ipfs/repo.lock failed: resource temporarily unavailable

The ipfs daemon works and I can browse to localhost:5001
but peergos on localhost:8000 is unavailable.

**Comment by ianopolous** [comment]
Hi @widwith ! Thanks for trying it out. That's a bug in ipfs. However we've just released a new version with an updated ipfs. Could you give it a try?
https://alpha.peergos.net/public/peergos/releases/v0.3.0

**Comment by widwith** [comment]
OK, I gave 0.3.0 a try, but no luck:

`INFO: $(ipfs p2p listen --allow-custom-protocol /http /ip4/127.0.0.1/tcp/8000) err: Error: lock /home/jeremy/.peergos/.ipfs/repo.lock: someone else has the lock`

I'm running java 11:
`$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)`

I started with a clean slate:
`rm -r ~/.peergos; 
rm ~/.cache/QmRkkTJ9CpAivdJcMMXxMT7krLXrBeRT77wyDPMKPd7YXn `

then launched Peergos-0.3.0.jar

Here's the console output during startup:
[https://zot.shorehub.com/cloud/bfrnr/Peergos/Peergos-0.3.0_startup.txt ](url)

**Comment by widwith** [comment]
OK, gave v0.3.0 a try but no luck.

Am running java 11:
`$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)`

And I started with a clean install:
`rm -r ~/.peergos; rm ~.cache/QmRkkTJ9CpAivdJcMMXxMT7krLXrBeRT77wyDPMKPd7YXn`

Then launched v0.3.0, but still lock file issues:
`INFO: $(ipfs p2p listen --allow-custom-protocol /http /ip4/127.0.0.1/tcp/8000) err: Error: lock /home/jeremy/.peergos/.ipfs/repo.lock: someone else has the lock`

Console output during startup:
[https://zot.shorehub.com/cloud/bfrnr/Peergos/Peergos-0.3.0_startup.txt](url)

**Comment by ianopolous** [comment]
Ah it looks like we need to update those instructions, there is a new required parameter
-admin-usernames
This is the list of usernames who can act as admins for this instance. The users don't have to exist yet. 

(The ipfs lock issue resolves itself automatically)

**Comment by widwith** [comment]
Thanks, works now with the new required parameter "-admin-usernames". Gave it a user, eg. "testuser" then brought up localhost:8000 (which now worked) and created the new user "testuser"
