### ISSUE TITLE
Selfhosted

### ISSUE THREAD

**Issue by jonaswre** [Peergos/Peergos#785]
First and foremost i must say this is a crazy great project.

This can be a backbone for almost any secure peer 2 peer application. I always thought that ipfs on its own is great for sharing public files. But I think its to hard to implement the whole security aspect for every application yourself, thats why peergos is so great. Do you guys have a eta for supporting selfhosting? Or can you provide some hints how to try selfhosting without a offically supported version. 

Thanks for the great work.

**Comment by ianopolous** [comment]
Hi @jonaswre! Thank you so much for the support. It means a lot for us to hear comments like yours. 

There are some people already self hosting. First you will need Java 11 or later installed. Then download the latest release from https://beta.peergos.net/public/peergos/releases or build the latest from the [web-ui](https://github.com/peergos/web-ui) repo with 
> ant dist

Then you can run the resulting jar with
> java -jar Peergos.jar daemon -admin-usernames $admin_usernames

where $admin_usernames is a comma separated list of usernames you want to be admins on this instance. You can change it any time, and the usernames don't have to exist yet. Admins mainly control how much storage space each user is allowed. There is a bunch of CLI commands which you can discover with 
> java -jar Peergos.jar -help

With that local node you can sign in to an account you created on another node, including beta.peergos.net. 
If you create a new account in the local node, then that user's data will be stored on your node. So if your node is offline, you won't be able to access your files though another node like beta.peergos.net. 

Feel free to jump into our matrix chat room and ask more questions if need be.

**Comment by jonaswre** [comment]
Thanks for your quick response.

Would a Dockerfile be accepted if I create one?

**Comment by ianopolous** [comment]
Thanks for the offer. I don't think docker buys us anything with our build system? We're already a single binary to run, assuming Java >= 11 is installed. If Java is an issue we can also make AOT compiled native builds which don't need Java (I haven't done that for v0.4.0 yet though).

**Comment by jonaswre** [comment]
I was not thinking about a devop perspective.

But from a sysops perspective docker has a lot of advantages over a single binary.
I think to properly support self-hosting a official docker image would make it much easier for people to host there own nodes. 

I might be a bit diffrent from your average joe. But I will be running my own node in a kubernetes cluster. So I'll creating a docker image anyways. But I always hate community images. Since ongoing support is not only dependent on the actually software but also on regular updates of that image. 

But I would be happy to know how you guys where thinking about distributing and updating running nodes once self-hosting is supported.

**Comment by jonaswre** [comment]
I've got another question regarding selfhosting. If I share a folder can that folder be backuped/cached on a diffrent node? Is there a way to let the ipfs node pin certain folders?

**Comment by ianopolous** [comment]
We hope to have a built-in updater that downloads updates over Peergos itself (and ideally using onion routing to prevent targeted attacks) eventually - at least for jar based deployment. For statically compiled native builds we're not sure. In general though, all releases and builds will be published in peergos itself. 

Regarding mirroring: at the moment we have commands to mirror an entire server or an individual user. The server doesn't have visibility into what is a file or folder. We could add a command to mirror a signing subspace of a user though (if you grant write access to something, it and its subtree get moved to a new signing subspace). Alternatively, if you are happy giving the mirror access to the plaintext then you could give it a path to a folder to mirror. 

If on the other hand you mean mirroring another user's folder/file such that you can access the last version of it if their server is offline, then yes we could copy the data into your space and use that copy if they are offline.

**Comment by gioppoluca** [comment]
Is there a way to build a private self hosted environment with more than one node?  Is the release you where mentioning enough or we need to add gateway or other components. In case of positive answer is there some documentation on how to configure the nodes to find each other?

**Comment by ianopolous** [comment]
The model in Peergos is each user has one server responsible for storing their data. That server can use any compatible blockstore for data (we have file based and S3 based working). E.g. if you can mount another distributed filesystem and run Peergos within it that should work today. As mentioned above, you can also live mirror your data on another instance.

**Comment by gioppoluca** [comment]
The use case I wanted to implement is a number of Public Administration entities that manage document for citizens.
Would a dedicated Peergos network (even if public but not linked to other networks) be a proper response in your opinion?

**Comment by ianopolous** [comment]
@gioppoluca We'd love to talk more about your use case. Can you drop us an email - peergos at peergos.org?
