### ISSUE TITLE
how to build a distributed storage system with peergos

### ISSUE THREAD

**Issue by pantaifeng** [Peergos/Peergos#817]
Hello, I'd like to ask you a question about peergos. I want to build peergos on my two computers to form a distributed storage system, but I don't know how to implement them. Now I can only run peergos on a single node. I want to know how to configure it so that the peergos / IPFs on the two computers can communicate.

**Comment by ianopolous** [comment]
The model in Peergos is that each user has one server responsible for storing their data. That server can in principle use any blockstore. We have implemented an S3 based blockstore which allows much bigger storage usage than a local harddisk. 

You can also mirror your data on another instance.
