### ISSUE TITLE
Is it possible to speed up files sending & encryption?

### ISSUE THREAD

**Issue by mkurczewski** [Peergos/Peergos#819]
I noticed a problem when sending many small files (over 2000 files with total weight of 35MB). It seems to lasts forever... or at least few hours 😱.

From what I see, you're using TweetNaCl for encryption but I'm just wondering if there are any better solutions 🤔 

For example, for Node version of TweetNaCl there's a https://www.npmjs.com/package/tweetnacl package that has improved performance in comparison to the 1:1 port. However, it's still poor comparing to  the _sodium_ for example - https://gist.github.com/jonasfj/af453cc2c569312ac59f. 

Unfortunately, the above is true only for Node, but from what I found on the web, the "original" _libsodium_ seems to be much faster than TweetNaCl. What do you think about it?

Or maybe there are other, better libraries that can use the GPU to increase the speed?

**Comment by ianopolous** [comment]
I'm pretty certain that encryption is not the bottle neck (symmetric encryption is very fast, and there is a limited amount of signing per upload). So far we've focused on optimising bandwidth for large files and we can comfortably hit 2 MiB/s upload to a server in a different country. We do need to spend time optimising uploading many small files. Bear in mind that files are padded to a multiple of 4 KiB, so if you have 2000 files that are all 100 bytes, that will actually use 4 KiB/100 ~ 40X more space than the original files (similar to what result on a real hard disk from using sectors). This is to protect the size of the files from being exposed. 

So the TLDR is there probably is some low hanging fruit to make many small file uploads faster, and we should look into it. Thanks for reporting it.

**Comment by mkurczewski** [comment]
To be more precise - those files were combination of text files with different "Lorem ipsum..." length, so the sizes were between 5KB and 36KB. Their total weight was 35,1 MB but on hard drive they allocated only 37,5 MB.

Anyway, good to hear you'll take care of that 💪

**Comment by mkurczewski** [comment]
@ianopolous I'm wondering if there's a possibility to use https://github.com/gpujs/gpu.js. It can be used in browser and it seems to be "implementable" with TweetNaCl 🤔 

This could give a real performance boost, even on slow GPU as all the cryptographic stuff is much more efficient on GPUs than on traditional CPUs.

**Comment by ianopolous** [comment]
You'll be pleased to hear we've just sped up everything in Peergos, some thing by as much as 20x (bulk small file upload and deletion).

**Comment by ianopolous** [comment]
Closing this because of the 20x speed up for bulk small file upload.
