### ISSUE TITLE
each user can use an ipfs instance (or cluster) with sufficient capability for their bandwidth requirements.

### ISSUE THREAD

**Issue by hu12305204** [Peergos/Peergos#821]
each user can use an ipfs instance (or cluster) with sufficient capability for their bandwidth requirements.
how can i  config  whit ipfs cluster?

**Comment by ianopolous** [comment]
Peergos installs and manages ipfs for you. We don't support ipfs cluster. However you can run secondary peergos instances and tell them to mirror your main instance.
