### ISSUE TITLE
Extend file properties

### ISSUE THREAD

**Issue by dsenko** [Peergos/Peergos#827]
Hi, I would like to extend file metadata. Let me know if good procedure is just to extend @JsType annotated class FileProperties in forked Peergos, or I can archive it with any other way, ex. saving "hidden" file on disc with additional properties mapped by ex. file name or smth like that.

Let me know please what approach would be compatible witht Peergos philosophy

**Comment by ianopolous** [comment]
If you point me to your code I can comment on it.

**Comment by dsenko** [comment]
i haven't got it yet, thats why I am asking which approach is correct - extending Java classes and so on, or just make trick storing some data in json files on user disc hidden from users :)

**Comment by ianopolous** [comment]
What are you trying to achieve?

**Comment by ianopolous** [comment]
Oh you mean like a recently accessed list or similar? yeah I'd just put that i a normal hidden file like most OSes do.
