### ISSUE TITLE
External integration

### ISSUE THREAD

**Issue by dsenko** [Peergos/Peergos#831]
Hi, is there any possibility to integrate peergos instance with external application? I mean having some kind of REST API in Peergos to integrate with (for ex. uploading files) without GWT js code. Just pure API for usage by other app written in any other language like python, java.

**Comment by ianopolous** [comment]
Czesc Dawid!

Our plan for 3rd party applications is they will be html5, and run in the browser, served directly from Peergos in a sandbox. Such apps wouldn't need gwt.js or anything like that and would have a simple REST api for talking with the main Peergos page. This ensures that there is no trusted server which can access your files (which we consider a vulnerability), which is the only way what you're asking for could be implemented. 

If you want something outside the browser you can use the Java client, or the CLI, or the FUSE mount.

**Comment by dsenko** [comment]
Thank you, it seems that it would not be possible even in the future to setup Peergos as any other standard microservice end consumed from other one without "peergos client", due to it's p2p nature and security assumptions

**Comment by warkocz** [comment]
Hello! What about using "somehow" Peergos's Java client classes in e.g. Android app directly... assuming that the device is trusted and Peergos credentials are kept in a safe place? Android Java client would contact Peergos server API via HTTPS.
Do you think that could work @ianopolous ?

**Comment by ianopolous** [comment]
Yep, that's totally inline with the security model. A trusted end user device is the only place where the password/keys are exposed. Even better would be if the app includes a peergos server (which just acts as a proxy+cache), then you aren't reliant on DNS and the TLS certificate authorities at all. 

I take it you're all in Warsaw? We should meet up next time I'm there.

**Comment by warkocz** [comment]
Definitely @ianopolous ! Let us know if you plan to visit Warsaw one day! :)
