### ISSUE TITLE
Git tags to mark releases

### ISSUE THREAD

**Issue by siriobalmelli** [Peergos/Peergos#872]
Would it be possible to push Git tags to mark releases?

This would make it possible to:

- build an exact match of the last release locally
- use GitHub notifications to know about new releases dropping

**Comment by ianopolous** [comment]
Yes we should do this. Note that you can already build an exact match as we put the git commit in the published jars at https://beta.peergos.net/public/peergos/releases (META-INF/MANIFEST.MF) along with the javac version

E.g. the current one has
> Version: web-ui/518f84b6904ee8a3f1a733627f3ef6e38b135270
> Javac-Version: javac 11.0.11

The commit is from the web-ui repo.
