### ISSUE TITLE
Failed uploads don't get cleaned up

### ISSUE THREAD

**Issue by Xnsamtr** [Peergos/Peergos#911]
On a self-hosted instance on version 0.6.0 I've had several failed uploads stick around for a few weeks now. Can't overwrite with a new upload (file exists error), removing the folder won't free up the space either, and the partially uploaded file can't be manually deleted because it's not visible.
Happened both with files that had an abort due to network error and ones where I manually interrupted the upload.

**Comment by ianopolous** [comment]
A work around to just get the file up is to rename it, or upload to a different folder. 

We try to automatically clean up failed uploads, but we should expose that in the UI to let people manually force it, or maybe do it periodically. (We hope to use it to enable continuing failed uploads too)

**Comment by Xnsamtr** [comment]
Renaming solves the uploading issue, but you still end up with increasing amounts of unusable space over time.
Both manual or periodical cleanup would solve this, so that's great.

**Comment by ianopolous** [comment]
There is now an option in the user menu to cleanup failed uploads.
