### ISSUE TITLE
Static website does not load properly

### ISSUE THREAD

**Issue by The-unknown-Shadowman** [Peergos/Peergos#930]
Dear Peergos-Team,
I just opened an account at peergos.net and uploaded a static website created with Publii (getpublii.com). All the fancy javascript does not work properly. It's like something in the background is stripping code. Uploading to regular ipfs does work. The website displays as it should. Deactivating some javascript like lazy loading helpts to load the images, but that's not very attractive. Am I something missing? I cannot give a link to the website because it's not official right now.
Thanks.

**Comment by ianopolous** [comment]
We have quite restrictive CSP by default. You can override this with a file in your web root like this: https://ianopolous.peergos.me/headers.json

Without looking at it that's my best guess.

**Comment by The-unknown-Shadowman** [comment]
That little file did the trick. You saved me alot of headaches. Thanks.
