### ISSUE TITLE
Error messages when trying to delete files and folders

### ISSUE THREAD

**Issue by The-unknown-Shadowman** [Peergos/Peergos#931]
I'm trying to delete some files and a empty folder. Most files work. Most folders work. But some cannot be deleted. I'm getting error messages like these:

Signed in using Google Chrome:
Error deleting file: $foldername: TypeError: Cannot read properties of null (reading 'startsWith')

Signed in using Firefox:
Error deleting file: $foldername: TypeError: trailer is null

**Comment by ianopolous** [comment]
That's odd. I've not seen that before. Is it reproducible for a given folder or file? Is it just folders or files too? If you have any stack traces from the browser console that would be helpful.

**Comment by The-unknown-Shadowman** [comment]
I tried moving one folder into another folder by drag and drop. The loading symbol appeared and didn't go away. I reloaded the page. The folder was copied but not deleted. Trying to delete the original folder didn't work. I deleted every file manually inside that folder. I thought, maybe it's a wrong perimission setting inside a file or something similar. That didn't work either. The folder wasn't deleteable.

The file was a simple textfile I created by using the onboard tools on yout webpage. I did some editing and sharing via secretlink. Afterwards I tried to delete the file. This didn't work.
I tried moving, deleting, renaming, changing the sharing permissions. Nothing worked to helpt with deleting.

How can I have a look at the console output. Everything happened directly on your webpage and not on a selfhosted server.

**Comment by ianopolous** [comment]
Thanks for the report. I think this is a recent regression. We're looking into it.

**Comment by ianopolous** [comment]
Ok that's fixed now. The deletion should work now.

**Comment by The-unknown-Shadowman** [comment]
Yes. I tried it and everythings works now. Thank you.
