### ISSUE TITLE
Error starting local daemon

### ISSUE THREAD

**Issue by jonaswre** [Peergos/Peergos#937]
> Looking up OS: windows 10
> Looking up architecture: amd64
> Connection refused: connect retrieving api/v0/id
> config --json Bootstrap [\"/ip4/172.104.157.121/tcp/4001/ipfs/QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF\",\"/ip6/2a01:7e01:0:0:f03c:92ff:fe26:f671/tcp/4001/ipfs/QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF\",\"/ip4/172.104.143.23/tcp/4001/ipfs/QmcoDbhCiVXGrWs6rwBvB59Gm44veo7Qxn2zmRnPw7BaCH\",\"/ip6/2a01:7e01:0:0:f03c:92ff:fee5:154a/tcp/4001/ipfs/QmcoDbhCiVXGrWs6rwBvB59Gm44veo7Qxn2zmRnPw7BaCH\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt\",\"/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ\",\"/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM\",\"/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu\",\"/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64\",\"/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd\",\"/ip6/2604:a880:1:20:0:0:203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM\",\"/ip6/2400:6180:0:d0:0:0:151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu\",\"/ip6/2604:a880:800:10:0:0:4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64\",\"/ip6/2a03:b0c0:0:1010:0:0:23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd\",\"/ip4/104.131.131.82/udp/4001/quic/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ\"]
> config Addresses.ProxyTarget /ip4/127.0.0.1/tcp/8003
> config --json Experimental.Libp2pStreamMounting true
> config --json Experimental.P2pHttpProxy true
> config Addresses.API /ip4/127.0.0.1/tcp/5001
> config Addresses.Gateway /ip4/127.0.0.1/tcp/8080
> config Addresses.AllowTarget http://127.0.0.1:8002
> config --json Addresses.Swarm [\"/ip4/0.0.0.0/tcp/4001\",\"/ip6/::/tcp/4001\"]
> daemon
> Connection refused: connect retrieving api/v0/id
> daemon
> daemon

it endlessly prints daemon

I dont know whats changed it was working on monday. Any old files that are left somewhere? I already cleared the ~/peergos folder.

**Comment by ianopolous** [comment]
what version is this? is it on windows?

**Comment by ianopolous** [comment]
Windows seems to not kill the ipfs process sometimes. Is the old ipfs process still running?

**Comment by jonaswre** [comment]
Latest v0.8.2 I cant see the ipfs process

**Comment by ianopolous** [comment]
I can give you a new build of the latest which includes several fixes, or you can wait until the next release. I'm working on another fix before doing the release.

**Comment by jonaswre** [comment]
I can wait, can you close this issue once you release so I will be notified?

**Comment by jonaswre** [comment]
I just realized there is the -log-to-console option

> java -jar Peergos.jar daemon -log-to-console

> Couldn't load native crypto library at , using pure Java version...
> To use the native linux-x86-64 crypto implementation use option -Djava.library.path=native-lib
> Apr 20, 2022 9:23:06 PM peergos.server.util.Logging init
> INFO: Logging to C:\Users\jonaswre\.peergos\peergos.0.log
> Looking up OS: windows 10
> Looking up architecture: amd64
> Connection refused: connect retrieving api/v0/id
> Apr 20, 2022 9:23:06 PM peergos.server.storage.IpfsWrapper build
> INFO: Using IPFS dir C:\Users\jonaswre\.peergos\.ipfs and IPFS binary C:\Users\jonaswre\.peergos\ipfs.exe
> Apr 20, 2022 9:23:06 PM peergos.server.storage.IpfsWrapper configure
> INFO: Setting ipfs bootstrap nodes [/ip4/172.104.157.121/tcp/4001/ipfs/QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF, /ip6/2a01:7e01:0:0:f03c:92ff:fe26:f671/tcp/4001/ipfs/QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF, /ip4/172.104.143.23/tcp/4001/ipfs/QmcoDbhCiVXGrWs6rwBvB59Gm44veo7Qxn2zmRnPw7BaCH, /ip6/2a01:7e01:0:0:f03c:92ff:fee5:154a/tcp/4001/ipfs/QmcoDbhCiVXGrWs6rwBvB59Gm44veo7Qxn2zmRnPw7BaCH, /dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN, /dnsaddr/bootstrap.libp2p.io/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa, /dnsaddr/bootstrap.libp2p.io/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb, /dnsaddr/bootstrap.libp2p.io/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt, /ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ, /ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM, /ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu, /ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64, /ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd, /ip6/2604:a880:1:20:0:0:203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM, /ip6/2400:6180:0:d0:0:0:151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu, /ip6/2604:a880:800:10:0:0:4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64, /ip6/2a03:b0c0:0:1010:0:0:23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd, /ip4/104.131.131.82/udp/4001/quic/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ]
> config --json Bootstrap [\"/ip4/172.104.157.121/tcp/4001/ipfs/QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF\",\"/ip6/2a01:7e01:0:0:f03c:92ff:fe26:f671/tcp/4001/ipfs/QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF\",\"/ip4/172.104.143.23/tcp/4001/ipfs/QmcoDbhCiVXGrWs6rwBvB59Gm44veo7Qxn2zmRnPw7BaCH\",\"/ip6/2a01:7e01:0:0:f03c:92ff:fee5:154a/tcp/4001/ipfs/QmcoDbhCiVXGrWs6rwBvB59Gm44veo7Qxn2zmRnPw7BaCH\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt\",\"/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ\",\"/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM\",\"/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu\",\"/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64\",\"/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd\",\"/ip6/2604:a880:1:20:0:0:203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM\",\"/ip6/2400:6180:0:d0:0:0:151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu\",\"/ip6/2604:a880:800:10:0:0:4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64\",\"/ip6/2a03:b0c0:0:1010:0:0:23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd\",\"/ip4/104.131.131.82/udp/4001/quic/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ\"]
> config Addresses.ProxyTarget /ip4/127.0.0.1/tcp/8003
> Apr 20, 2022 9:23:07 PM peergos.server.storage.IpfsWrapper configure
> INFO: Running ipfs config
> config --json Experimental.Libp2pStreamMounting true
> config --json Experimental.P2pHttpProxy true
> config Addresses.API /ip4/127.0.0.1/tcp/5001
> config Addresses.Gateway /ip4/127.0.0.1/tcp/8080
> config Addresses.AllowTarget http://127.0.0.1:8002
> config --json Addresses.Swarm [\"/ip4/0.0.0.0/tcp/4001\",\"/ip6/::/tcp/4001\"]
> Connection refused: connect retrieving api/v0/id
> Apr 20, 2022 9:23:08 PM peergos.server.storage.IpfsWrapper start
> INFO: Starting ipfs daemon
> daemon
> Apr 20, 2022 9:23:08 PM peergos.server.util.Logging log
> INFO: $(ipfs daemon) err: panic: failed to listen on any addresses: [listen tcp4 0.0.0.0:4001: bind: An attempt was made to access a socket in a way forbidden by its access permissions. listen tcp6 [::]:4001: bind: An attempt was made to access a socket in a way forbidden by its access permissions.]
> Apr 20, 2022 9:23:08 PM peergos.server.util.Logging log
> INFO: $(ipfs daemon) err:
> Apr 20, 2022 9:23:08 PM peergos.server.util.Logging log
> INFO: $(ipfs daemon) err: goroutine 1 [running]:
> Apr 20, 2022 9:23:08 PM peergos.server.util.Logging log
> INFO: $(ipfs daemon) err: main.main()
> Apr 20, 2022 9:23:08 PM peergos.server.util.Logging log
> INFO: $(ipfs daemon) err:       /home/ian/ipfs-nucleus/daemon/ipfs-nucleus.go:158 +0x1133
> Apr 20, 2022 9:23:08 PM peergos.server.storage.IpfsWrapper run
> WARNING: IPFS exited with return-code 2
> Apr 20, 2022 9:23:09 PM peergos.server.util.Logging lambda$init$0
> SEVERE: Uncaught Exception in thread 1:main
> java.lang.RuntimeException: java.lang.IllegalStateException: ipfs daemon terminated with return code 2
>         at peergos.server.Main.startPeergos(Main.java:741)
>         at peergos.server.Command.main(Command.java:75)
>         at peergos.server.Command.main(Command.java:63)
>         at peergos.server.Main.main(Main.java:901)
> Caused by: java.lang.IllegalStateException: ipfs daemon terminated with return code 2
>         at peergos.server.storage.IpfsWrapper.waitForDaemon(IpfsWrapper.java:179)
>         at peergos.server.storage.IpfsWrapper.launchAndManage(IpfsWrapper.java:455)
>         at peergos.server.Main.startIpfs(Main.java:812)
>         at peergos.server.Command.main(Command.java:75)
>         at peergos.server.Main.startPeergos(Main.java:524)
>         ... 3 more
> 
> Apr 20, 2022 9:23:09 PM peergos.server.storage.IpfsWrapper start
> INFO: Starting ipfs daemon
> daemon
> Apr 20, 2022 9:23:10 PM peergos.server.util.Logging log
> INFO: $(ipfs daemon) err: panic: failed to listen on any addresses: [listen tcp4 0.0.0.0:4001: bind: An attempt was made to access a socket in a way forbidden by its access permissions. listen tcp6 [::]:4001: bind: An attempt was made to access a socket in a way forbidden by its access permissions.]
> Apr 20, 2022 9:23:10 PM peergos.server.util.Logging log
> INFO: $(ipfs daemon) err:
> Apr 20, 2022 9:23:10 PM peergos.server.util.Logging log
> INFO: $(ipfs daemon) err: goroutine 1 [running]:
> Apr 20, 2022 9:23:10 PM peergos.server.util.Logging log
> INFO: $(ipfs daemon) err: main.main()
> Apr 20, 2022 9:23:10 PM peergos.server.util.Logging log
> INFO: $(ipfs daemon) err:       /home/ian/ipfs-nucleus/daemon/ipfs-nucleus.go:158 +0x1133
> Apr 20, 2022 9:23:10 PM peergos.server.storage.IpfsWrapper run
> WARNING: IPFS exited with return-code 2
> Apr 20, 2022 9:23:11 PM peergos.server.storage.IpfsWrapper start
> INFO: Starting ipfs daemon
> daemon

**Comment by ianopolous** [comment]
This looks like ipfs isn't allowed to listen on port 4001:
> INFO: $(ipfs daemon) err: panic: failed to listen on any addresses: [listen tcp4 0.0.0.0:4001: bind: An attempt was made to access a socket in a way forbidden by its access permissions. listen tcp6 [::]:4001: bind: An attempt was made to access a socket in a way forbidden by its access permissions.]

**Comment by ianopolous** [comment]
The new release is out: https://peergos.net/public/peergos/releases/v0.9.0
