### ISSUE TITLE
ARM64 Support? 

### ISSUE THREAD

**Issue by jonaswre** [Peergos/Peergos#938]
I tried to run peergos on my macbook m1. 

No errors 

> Couldn't load native crypto library at /Users/jonaswre/Desktop/native-lib/libtweetnacl.so, using pure Java version...
To use the native linux-x86-64 crypto implementation use option -Djava.library.path=native-lib
Looking up OS: mac os x
Looking up architecture: aarch64

And then peergos just stops. 

> java 17.0.3 2022-04-19 LTS
> Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111)
> Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing)

This is my java version.

**Comment by jonaswre** [comment]
> Couldn't load native crypto library at /Users/jonaswre/Desktop/native-lib/libtweetnacl.so, using pure Java version...
> To use the native linux-x86-64 crypto implementation use option -Djava.library.path=native-lib
> Apr 20, 2022 9:17:12 PM peergos.server.util.Logging init
> INFO: Logging to /Users/jonaswre/.peergos/peergos.0.log
> Looking up OS: mac os x
> Looking up architecture: aarch64
> Apr 20, 2022 9:17:12 PM peergos.server.util.Logging lambda$init$0
> SEVERE: Uncaught Exception in thread 1:main
> java.lang.RuntimeException: java.lang.IllegalArgumentException: No enum constant peergos.server.storage.IpfsInstaller.DownloadTarget.DARWIN_AARCH64
> 	at peergos.server.Main.startPeergos(Main.java:741)
> 	at peergos.server.Command.main(Command.java:75)
> 	at peergos.server.Command.main(Command.java:63)
> 	at peergos.server.Main.main(Main.java:901)
> Caused by: java.lang.IllegalArgumentException: No enum constant peergos.server.storage.IpfsInstaller.DownloadTarget.DARWIN_AARCH64
> 	at java.base/java.lang.Enum.valueOf(Enum.java:273)
> 	at peergos.server.storage.IpfsInstaller$DownloadTarget.valueOf(IpfsInstaller.java:23)
> 	at peergos.server.storage.IpfsInstaller.getForPlatform(IpfsInstaller.java:179)
> 	at peergos.server.storage.IpfsInstaller.ensureInstalled(IpfsInstaller.java:168)
> 	at peergos.server.Main.lambda$static$0(Main.java:71)
> 	at peergos.server.Command.main(Command.java:75)
> 	at peergos.server.Main.startPeergos(Main.java:523)
> 	... 3 more

I guess ipfs is not made of arm64 / m1

**Comment by ianopolous** [comment]
We can add a macos arm64 build of ipfs-nucleus. I'll put it in the upcoming release.

**Comment by jonaswre** [comment]
I guess im excited for the upcoming release 😆

**Comment by jonaswre** [comment]
The daemon works now, but the fuse throws an error.

> java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
> 	at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:48)
> 	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:325)
> 	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:304)
> 	at ru.serce.jnrfuse.AbstractFuseFS.<init>(AbstractFuseFS.java:61)
> 	at ru.serce.jnrfuse.FuseStubFS.<init>(FuseStubFS.java:23)
> 	at peergos.server.fuse.PeergosFS.<init>(PeergosFS.java:47)
> 	at peergos.server.Main.startFuse(Main.java:790)
> 	at peergos.server.Command.main(Command.java:75)
> 	at peergos.server.Command.main(Command.java:63)
> 	at peergos.server.Main.main(Main.java:902)
> Caused by: java.lang.ExceptionInInitializerError
> 	at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:58)
> 	at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
> 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
> 	at java.base/java.lang.Class.newInstance(Class.java:645)
> 	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
> 	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
> 	at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
> 	at jnr.ffi.LibraryLoader.create(LibraryLoader.java:73)
> 	at ru.serce.jnrfuse.AbstractFuseFS.<init>(AbstractFuseFS.java:40)
> 	... 6 more
> Caused by: java.lang.IllegalStateException: Can't overwrite cause with java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/20/mwfb3fps7d3d9nb_znsmkvq00000gn/T/jffi7580042110309499670.dylib
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
> 	at java.base/java.lang.Runtime.load0(Runtime.java:755)
> 	at java.base/java.lang.System.load(System.java:1953)
> 	at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:371)
> 	at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:258)
> 	at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:444)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Class.java:467)
> 	at com.kenai.jffi.Init.load(Init.java:68)
> 	at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
> 	at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
> 	at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
> 	at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
> 	at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
> 	at com.kenai.jffi.Type.resolveSize(Type.java:155)
> 	at com.kenai.jffi.Type.size(Type.java:138)
> 	at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:187)
> 	at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
> 	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:66)
> 	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
> 	at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:62)
> 	at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:58)
> 	at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
> 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
> 	at java.base/java.lang.Class.newInstance(Class.java:645)
> 	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
> 	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
> 	at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
> 	at jnr.ffi.LibraryLoader.create(LibraryLoader.java:73)
> 	at ru.serce.jnrfuse.AbstractFuseFS.<init>(AbstractFuseFS.java:40)
> 	at ru.serce.jnrfuse.FuseStubFS.<init>(FuseStubFS.java:23)
> 	at peergos.server.fuse.PeergosFS.<init>(PeergosFS.java:47)
> 	at peergos.server.Main.startFuse(Main.java:790)
> 	at peergos.server.Command.main(Command.java:75)
> 	at peergos.server.Command.main(Command.java:63)
> 	at peergos.server.Main.main(Main.java:902)
> 
> 	at java.base/java.lang.Throwable.initCause(Throwable.java:463)
> 	at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:252)
> 	at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
> 	at com.kenai.jffi.Type.resolveSize(Type.java:155)
> 	at com.kenai.jffi.Type.size(Type.java:138)
> 	at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:187)
> 	at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
> 	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:66)
> 	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
> 	at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:62)
> 	... 20 more
> Caused by: java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/20/mwfb3fps7d3d9nb_znsmkvq00000gn/T/jffi7580042110309499670.dylib
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
> 	at java.base/java.lang.Runtime.load0(Runtime.java:755)
> 	at java.base/java.lang.System.load(System.java:1953)
> 	at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:371)
> 	at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:258)
> 	at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:444)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Class.java:467)
> 	at com.kenai.jffi.Init.load(Init.java:68)
> 	at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
> 	at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
> 	at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
> 	at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
> 	at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
> 	at com.kenai.jffi.Type.resolveSize(Type.java:155)
> 	at com.kenai.jffi.Type.size(Type.java:138)
> 	at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:187)
> 	at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
> 	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:66)
> 	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
> 	at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:62)
> 	at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:58)
> 	at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
> 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
> 	at java.base/java.lang.Class.newInstance(Class.java:645)
> 	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
> 	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
> 	at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
> 	at jnr.ffi.LibraryLoader.create(LibraryLoader.java:73)
> 	at ru.serce.jnrfuse.AbstractFuseFS.<init>(AbstractFuseFS.java:40)
> 	at ru.serce.jnrfuse.FuseStubFS.<init>(FuseStubFS.java:23)
> 	at peergos.server.fuse.PeergosFS.<init>(PeergosFS.java:47)
> 	at peergos.server.Main.startFuse(Main.java:790)
> 	at peergos.server.Command.main(Command.java:75)
> 	at peergos.server.Command.main(Command.java:63)
> 	at peergos.server.Main.main(Main.java:902)
> 
> 	at com.kenai.jffi.Foreign.newLoadError(Foreign.java:72)
> 	at com.kenai.jffi.Foreign.access$300(Foreign.java:42)
> 	at com.kenai.jffi.Foreign$InValidInstanceHolder.getForeign(Foreign.java:98)
> 	at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
> 	at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
> 	... 28 more
> Caused by: java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/20/mwfb3fps7d3d9nb_znsmkvq00000gn/T/jffi7580042110309499670.dylib
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
> 	at java.base/java.lang.Runtime.load0(Runtime.java:755)
> 	at java.base/java.lang.System.load(System.java:1953)
> 	at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:371)
> 	at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:258)
> 	at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:444)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Class.java:467)
> 	at com.kenai.jffi.Init.load(Init.java:68)
> 	at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
> 	at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
> 	at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
> 	at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
> 	at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
> 	at com.kenai.jffi.Type.resolveSize(Type.java:155)
> 	at com.kenai.jffi.Type.size(Type.java:138)
> 	at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:187)
> 	at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
> 	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:66)
> 	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
> 	at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:62)
> 	at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:58)
> 	at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
> 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
> 	at java.base/java.lang.Class.newInstance(Class.java:645)
> 	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
> 	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
> 	at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
> 	at jnr.ffi.LibraryLoader.create(LibraryLoader.java:73)
> 	at ru.serce.jnrfuse.AbstractFuseFS.<init>(AbstractFuseFS.java:40)
> 	at ru.serce.jnrfuse.FuseStubFS.<init>(FuseStubFS.java:23)
> 	at peergos.server.fuse.PeergosFS.<init>(PeergosFS.java:47)
> 	at peergos.server.Main.startFuse(Main.java:790)
> 	at peergos.server.Command.main(Command.java:75)
> 	at peergos.server.Command.main(Command.java:63)
> 	at peergos.server.Main.main(Main.java:902)
> 
> 	at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:270)
> 	at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:444)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Class.java:467)
> 	at com.kenai.jffi.Init.load(Init.java:68)
> 	at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
> 	at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
> 	... 30 more
>

**Comment by ianopolous** [comment]
I'm not sure if the fuse library we use (https://github.com/SerCeMan/jnr-fuse) supports arm64 Macs.

**Comment by ProgrammingPlanet** [comment]
Hi, I'm having same issue on Linux arm64
Anyone can help?

What I have tried out -
 git clone https://github.com/Peergos/web-ui
 cd web-ui
 ant dist
 cd server
 java -jar Peergos.js

Couldn't load native crypto library at path-to-project/peergos/server/native-lib/libtweetnacl.so

**Comment by moinologics** [comment]
Program exists after this 
![Uploading Screenshot_20221121-220924_Termius.png…]()

**Comment by ianopolous** [comment]
you need to run the daemon command, see https://github.com/peergos/peergos#usage---self-hosting
