### ISSUE TITLE
Allow folder deletion in shell

### ISSUE THREAD

**Issue by jonaswre** [Peergos/Peergos#961]
When uploading folders is possible you will need to be able to delete these folders. 

Is is not urgent at the moment

**Comment by ianopolous** [comment]
I'm not sure I follow. The rm command can delete folders.

**Comment by jonaswre** [comment]
I tried in 0.9.x and it said folder deletion is not supported

**Comment by ianopolous** [comment]
I added it on the 9th May. So it's in the 0.10.0 release.
