### ISSUE TITLE
File not loding in Sandbox

### ISSUE THREAD

**Issue by jonaswre** [Peergos/Peergos#967]
I have two files, one m4b and a mp3. 

If I fetch the mp3 I get a 200 status code as response if do the exact same code with my m4b I get a 404 as response.

Not sure what I can say more the m4b files is much larger. (400MB)
Any ideas what the problem could be?

**Comment by kevodwyer** [comment]
I was able to replicate in chrome.  Chrome does not like it when >100MiB is sent to the sandbox service worker in 1 action. As a workaround until I can figure out how to not overload the sw is to use a range request.

	let headers = {Range: 'bytes={start}-{end}'};	
	fetch('/peergos-api/v0/data/dome.file', { method: 'GET', headers: headers })

Make sure to check the response as what you get back may include more data then what you asked for as it is optimised for streaming video

**Comment by jonaswre** [comment]
Thanks a lot. 

I'm not sure what's you mean by check the response. You mean I'll have to manually request all bytes. So I'll need to request all bytes from 0 to eof myself? 
And chunk size smaller 100 mb is fine?

**Comment by kevodwyer** [comment]
fetching a file < 100MiB is fine. Above that streaming with a range request is the way to go for now. The reponse for a range request: Status code 206 and response headers like:
accept-ranges: bytes
content-length: 1048576
Content-Range: bytes 0-1048575/235050515

I will update docs to make clear drive api is required only for an App's data directory. Thanks for the find.
