### ISSUE TITLE
Interested in Building On Peergos And Have Questions

### ISSUE THREAD

**Issue by Timothy-AthenaProtocol** [Peergos/Peergos#968]
Hello all I am with the Athena Protocol and working to build data sovereign information infrastructure solutions. We are interested in the work you are doing and have been following your development. I have been testing the free version of your service for some time and the speeds have much improved so congratulations. We are very aligned with your mission to prevent unethical data mining services like friend mapping, and I am interested to learn how Athena Protocol might build on top of a Peergos API were there one. 

If this is not the best place to discuss this please let me know where I should direct my efforts. This was the only method I could find. 

Looking forward to hearing from you and keep up the excellent work.

**Comment by jonaswre** [comment]
Hi, I can say anything about the API but there is a Matrix Chat room https://matrix.to/#/#peergos-chat:matrix.org that's always a good place to get in contact..
